import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Phone, Menu, X, Wrench, Droplets, Flame, Waves, ShowerHead, Pipette, Check, MapPin, Plus, Minus, HardHat } from 'lucide-react';
import './styles.css';
import { EnquiryForm, Gallery, MobileContactBar, Process, ReviewsAndCredentials, assetUrl, useEntranceAnimations } from './Enhancements';
import { siteContent } from './site-content';

const services = [
  [Wrench, 'Plumbing & maintenance', 'From new installations to the everyday fixes. We keep your plumbing working as it should.'],
  [Waves, 'Blocked drains', 'Slow sink? Blocked drain? Let’s get things flowing again. Sewer and stormwater drainage, sorted.'],
  [ShowerHead, 'Hot water', 'Cold showers aren’t for everyone. Get in touch about your hot water installation or repairs.'],
  [Flame, 'Gas fitting & repairs', 'LPG and gas fitting, installations and repairs for your home or business.'],
  [Droplets, 'Taps, toilets & burst pipes', 'Dripping taps, running toilets and surprise leaks. Small annoyances or big problems, we’re here to help.'],
  [Pipette, 'Backflow & TMV', 'Backflow prevention and thermostatic mixing valve services. Specialist plumbing made straightforward.'],
];
const faqs = [
  ['Where do you work?', 'We’re based in Glenmore Park and service the Greater Sydney region. Tell us your suburb when you get in touch.'],
  ['Can I get a quote?', 'Absolutely. Call 0412 629 823 or send us an enquiry with a few details about the job to discuss a free quote.'],
  ['What if it’s an emergency?', 'For burst pipes or urgent plumbing issues, call us directly on 0412 629 823 to check availability.'],
  ['Do you handle small jobs?', 'Yes. From dripping taps and toilet repairs to installations and drainage, we do all kinds of plumbing stuff.'],
];
function Brand() { return <a className="brand" href="#" aria-label="Ironhat Plumbing home"><HardHat size={35} strokeWidth={1.6}/><span>IRONHAT<small>PLUMBING</small></span></a>; }
function App() {
  const [menu, setMenu] = useState(false), [faq, setFaq] = useState(null), [selected, setSelected] = useState('');
  useEntranceAnimations();
  return <>
    <div className="topbar"><span>YOUR LOCAL PLUMBER. SYDNEY WIDE.</span><a href="tel:0412629823">Need a hand? <span>0412 629 823 ↗</span></a></div>
    <header className="header"><Brand/><nav className={menu ? 'nav open' : 'nav'} aria-label="Main navigation">{[['Services','services'],...(siteContent.projects.length || import.meta.env.DEV ? [['Our work','projects']] : []),['About us','about'],['Service areas','areas']].map(([text,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{text}</a>)}<a href="#contact" className="button dark" onClick={()=>setMenu(false)}>Let’s talk plumbing <ArrowUpRight size={17}/></a></nav><button className="menu-button" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
    <main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> GLENMORE PARK & GREATER SYDNEY</p><h1>Good plumbing.<br/><span>No fuss.</span></h1><p className="hero-description">Big jobs. Small fixes. All the plumbing stuff.<br/>Straight-up service from a local who cares.</p><div className="hero-actions"><a className="button orange" href="#contact">Get a free quote <ArrowUpRight size={20}/></a><a className="phone-link" href="tel:0412629823"><Phone size={18}/> 0412 629 823</a></div><div className="hero-proof"><span><Check size={16}/> Locally owned</span><span><Check size={16}/> 10+ years’ experience</span><span><Check size={16}/> No runaround</span></div></div><div className="hero-photo"><img src={import.meta.env.BASE_URL + 'plumbing.jpg'} alt="Plumbing pipework and fittings"/><div className="photo-shade"/><span className="photo-caption">THE RIGHT TOOLS. THE RIGHT ATTITUDE.</span><div className="photo-stamp"><HardHat size={32}/><span>LOCAL HANDS.<br/>SOLID WORK.</span><ArrowUpRight size={24}/></div></div><div className="hero-bottom"><span>PLUMBING DONE PROPERLY.</span><a href="#services">See what we do <ArrowRight size={17}/></a></div></section>
      <section id="services" className="section services"><div className="section-heading"><div><p className="eyebrow">01 / WHAT WE DO</p><h2>We do plumbing stuff.<br/><span>All kinds of it.</span></h2></div><p>From that tap that won’t stop dripping to a whole new installation. A practical solution for every plumbing problem.</p></div><div className="service-grid">{services.map(([Icon,title,description],i)=><a key={title} className="service-card" href="#contact" onClick={()=>setSelected(title)}><div className="service-top"><Icon size={29} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{title}</h3><p>{description}</p><span className="service-link">Let’s get it sorted <ArrowUpRight size={20}/></span></a>)}</div></section>
      <Process/>
      <Gallery/>
      <section id="about" className="about"><div className="about-art">{siteContent.samPhoto && <img className="sam-photo" src={assetUrl(siteContent.samPhoto)} alt="Sam Eisenhuth, founder of Ironhat Plumbing" loading="lazy"/>}<span className="art-label">EST. 2021 · GLENMORE PARK, NSW</span><HardHat className="big-hat" strokeWidth={.7}/><div className="art-type">IRON<br/>HAT<span>BUILT ON GOOD WORK.</span></div></div><div className="about-copy"><p className="eyebrow">02 / THE PERSON BEHIND THE PIPES</p><h2>Your local plumbing professional.<br/>A job done right.</h2><p>Meet Sam Eisenhuth, the founder of Ironhat Plumbing. With over 10 years of experience in maintenance and construction plumbing, Sam started Ironhat in 2021 with a simple idea: keep it honest and do good work.</p><p>We’re a small local business delivering fast, affordable plumbing services across Greater Sydney. Clear communication, care for your home, and no bullshit.</p><a className="text-link" href="#contact">Say g’day to Sam <ArrowUpRight size={20}/></a><div className="about-facts"><div><strong>10+</strong><span>Years of experience</span></div><div><strong>2021</strong><span>Our story started</span></div><div><strong>Sydney</strong><span>Our backyard</span></div></div></div></section>
      <ReviewsAndCredentials/>
      <section id="areas" className="section areas"><div><p className="eyebrow">03 / IN YOUR NEIGHBOURHOOD</p><h2>Local roots.<br/>Sydney-wide reach.</h2><p>Based in Glenmore Park. On the tools across Greater Sydney.<br/>Get in touch to chat about a job in your area.</p><a className="text-link" href="tel:0412629823">Check your suburb with us <ArrowUpRight size={20}/></a></div><div className="area-panel"><MapPin size={34}/><span>OUR HOME BASE</span><h3>Glenmore Park</h3><p>Greater Sydney, New South Wales</p><div className="area-line"/><div className="area-foot"><span>We service Sydney wide.</span><ArrowUpRight size={26}/></div></div></section>
      <section className="section faq"><div><p className="eyebrow">A FEW GOOD QUESTIONS</p><h2>Before you<br/>give us a bell.</h2></div><div className="faq-list">{faqs.map(([question,answer],i)=><div className="faq-item" key={question}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={'faq-'+i}>{question}{faq===i?<Minus size={19}/>:<Plus size={19}/>}</button>{faq===i&&<p id={'faq-'+i}>{answer}</p>}</div>)}</div></section>
      <section id="contact" className="contact"><div><p className="eyebrow">04 / LET’S GET IT SORTED</p><h2>Plumbing problem?<br/><span>We’re all ears.</span></h2><p>Tell us what’s going on. We’ll chat through the job<br/>and help you take the next step.</p><a className="contact-phone" href="tel:0412629823">0412 629 823 <ArrowUpRight/></a><a className="contact-email" href="mailto:info@ironhatplumbing.com.au">info@ironhatplumbing.com.au</a><p className="urgent"><Phone size={17}/> Something urgent? Give us a call.</p></div><EnquiryForm services={services} selected={selected} setSelected={setSelected}/></section>
    </main><MobileContactBar/><footer><div className="footer-main"><Brand/><p>Good plumbing. Good people. No fuss.</p><a href="#">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ironhat Plumbing Pty Ltd</span><span>ABN 47 680 672 100</span><span>Glenmore Park · Sydney wide</span></div></footer>
  </>;
}
createRoot(document.getElementById('root')).render(<App/>);
